// Frontend configuration - Auto-generated from environment
// Generated by generate_config.py - Do not edit manually

window.APP_CONFIG = {
    API_BASE_URL: 'http://localhost:8000',
    API_VERSION: 'v1',
    DEFAULT_MODEL: 'claude-3-5-haiku-20241022',
    DEFAULT_TEMPERATURE: 0.1,
    
    // Environment info
    ENVIRONMENT: 'development',
    GENERATED_AT: '2025-08-10T10:52:37.480009'
};

console.log('Frontend config loaded:', window.APP_CONFIG);
