#!/usr/bin/env python3
"""
Generate frontend configuration from environment variables.

USAGE:
    Run this script from the project root directory:
    python generate_config.py

REQUIREMENTS:
    - Must be run from the project root (where .env file is located)
    - AILA_API_FAST_API_PORT must be set in .env file
    - AILA_FAST_API_HOST is optional (defaults to localhost)

This script will create/update frontend/config.js with current environment settings.
"""

import os
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv


def generate_frontend_config() -> None:
    # Verify we're in the project root
    if not Path(".env").exists():
        print("❌ Error: .env file not found!")
        print("   Please run this script from the project root directory where .env is located.")
        print("   Example: python generate_config.py")
        sys.exit(1)

    # Load environment variables
    load_dotenv()

    # Get configuration values
    api_port = os.getenv("AILA_API_FAST_API_PORT")
    if api_port is None:
        raise ValueError("❌ AILA_API_FAST_API_PORT must be set in .env file")

    api_host = os.getenv("AILA_FAST_API_HOST", "localhost")
    if not api_host:
        raise ValueError("❌ AILA_FAST_API_HOST must be set in .env file or default to 'localhost'")

    api_base_url = f"http://{api_host}:{api_port}"

    # Generate config.js content
    config_content = f"""// Frontend configuration - Auto-generated from environment
// Generated by generate_config.py - Do not edit manually

window.APP_CONFIG = {{
    API_BASE_URL: '{api_base_url}',
    API_VERSION: 'v1',
    DEFAULT_MODEL: 'claude-3-5-haiku-20241022',
    DEFAULT_TEMPERATURE: 0.1,
    
    // Environment info
    ENVIRONMENT: '{os.getenv("ENVIRONMENT", "development")}',
    GENERATED_AT: '{datetime.now().isoformat()}'
}};

console.log('Frontend config loaded:', window.APP_CONFIG);
"""

    # Write to frontend/static directory for deployment setup
    static_dir = Path("frontend") / "static"
    static_dir.mkdir(exist_ok=True)

    config_path = static_dir / "config.js"
    with open(config_path, "w") as f:
        f.write(config_content)

    print(f"✅ Generated frontend config: {config_path}")
    print(f"   API Base URL: {api_base_url}")
    print(f"   Environment: {os.getenv('ENVIRONMENT', 'development')}")


if __name__ == "__main__":
    generate_frontend_config()
