services:
  aila-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount .env file for API keys
      - ./.env:/app/.env:ro
      # Mount data directory for document uploads
      - ./data:/app/data
      # Mount results directory for outputs
      - ./results:/app/results
      # Mount cache directory for performance
      - ./cache:/app/cache
      # Mount logs directory for debugging
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - aila-api
  #   restart: unless-stopped
